import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { Datum, Person, Address } from '@/types'
import { GetStaticProps, NextPage } from 'next'

const inter = Inter({ subsets: ['latin'] })

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch('https://fakerapi.it/api/v1/persons?_quantity=10')
  const {data} : Person = await res.json()

  return {
    props: {
      people: data
    }
  }
}

const Home: NextPage<{people : Datum[]}> = ({people}) => {
  return (
    <>
      <Head>
        <title>Social Mockida</title>
        <meta name="description" content="Generated by Faker API" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ul>
        {people.map((person) => (
          <li>{person.firstname}</li>
        ))}
      </ul>

    </>
  )
}

export default Home
