import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { Datum, Person, Address, PostInfo, Post } from '@/types'
import { GetStaticProps, NextPage } from 'next'
import { ResponseCookies } from 'next/dist/server/web/spec-extension/cookies'

const inter = Inter({ subsets: ['latin'] })

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch('https://fakerapi.it/api/v1/persons?_quantity=10')
  const peopleData : Person = await res.json()
  
  const res2 = await fetch('https://fakerapi.it/api/v1/texts?_quantity=10&_characters=50')
  const postData : PostInfo = await res2.json()

  return {
    props: {
      peopleData,
      postData
    }
  }
}


const Home: NextPage<{peopleData : Person, postData: PostInfo}> = ({peopleData, postData}) => {
  return (
    <>
      <Head>
        <title>Social Mockida</title>
        <meta name="description" content="Generated by Faker API" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className='main-header'>
        <h3 className='title-header'>Social Mockida</h3>
        <section className='userOptions'>
        <h4 className='login-header'>Login</h4>
        <h4 className='signup-header'>Sign Up</h4>
        </section>
      </header>
      <ul className='main-content'>
        {peopleData.data.map((person) => {
          return (
            <div key={person.id} className='content-items'>
              <Image
                className='content-image' 
                unoptimized
                src={person.image}
                alt={person.firstname}
                width="50"
                height="50"
                />
              <h5 className='content-name'>{person.firstname} {person.lastname}</h5>
            {postData.data.map((post, id) => {
              return (
                <p key={id} className='content-post'>{post.content}</p>
                )
              })}
            </div>
          )
        })}
      </ul>

    </>
  )
}

export default Home
